export const mobileNavItems = [
  {
    path: "/",
    label: "home",
  },
  {
    path: "/about",
    label: "about",
  },
  {
    path: "/work",
    label: "work",
  },
  {
    path: "/contact",
    label: "contact",
  },
].map((n, idx) => ({ ...n, id: idx + 1 }));

/*
This code defines an array of mobile navigation items, each with a path, label, and a unique id.
The array is exported as mobileNavItems, which can be used in other parts of the application.
The items include "home", "about", and "contact" pages, each with a corresponding path.
The id is generated by adding 1 to the index of the item in the array.
This allows for easy mapping and rendering of the items in a navigation component.
The array can be used to dynamically generate navigation links in a mobile-friendly format.
The use of map() allows for easy modification of the items in the future, if needed.
The items are structured as objects, making it easy to access their properties.
This structure is useful for creating a responsive navigation menu that can adapt to different screen sizes.
The array can be easily extended to include more navigation items in the future.
The use of a unique id for each item allows for better tracking and management of the navigation items.
The array can be imported and used in various components throughout the application.
This code is a simple and efficient way to manage mobile navigation items in a web application.
The items can be styled and rendered in a consistent manner across different components.
The use of a separate file for navigation items helps keep the code organized and maintainable.
The array can be easily modified to include additional properties for each item, if needed.
*/
