import Header from "./components/Header/Header";
import Main from "./components/Main/Main";
import Footer from "./components/Footer/Footer";
import ClientLayout from "./components/ClientLayout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/rgm1dlw.css" />
      </head>
      <body className="set font-[sofia-pro,_sans-serif] font-medium not-italic text-slate-100/70 antialiased">
        <ClientLayout>
          <div className="flex min-h-screen flex-col space-y-4 bg-gradient-to-b from-[rgba(12,12,39,0.83)] to-[rgba(0,2,8,0.5)]">
            <Header />
            <Main>{children}</Main>
            <Footer />
          </div>
        </ClientLayout>
      </body>
    </html>
  );
}
